#first time access need from local server
# add trsust domains
# add to config.php for ntfs: 'check_data_directory_permissions' => false,

version: "2.1"

volumes:
  db:

services:
  db:
    image: jsurf/rpi-mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=m2j3v6
      - MYSQL_PASSWORD=m2j3v6
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
  app:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /mnt/mydisk/data/nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=m2j3v6
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    restart: unless-stopped
